%% IEEE VTS Motor Vehicles Challenge 2023
% A Multi-physical Benchmark Problem for Next Generation Energy Management Algorithms
%
%  University of California, Merced | German Aerospace Center (DLR)

%% Introduction
% This brief report has been designed so as to demonstrate the performance
% of the designed Energy Management Algorithm (EMA) by the competitors.
% Please see bellow for more information on the evaluation:
% 
% The selected track corresponds to Track:
load('performance.mat');
Track_Info = performance.info

%% Performance Metrics
% Performance metrics for the corresponding track are as follows:
Performance = performance.Scores

%% Results
% * *Reference track*
%
% <<fig1.png>>
%
% * *Control Inputs Generated by the EMA*
%
% <<fig2.png>>
%
% * *State-of-Charge and Temperature of the Battery Pack*
%
% <<fig3.png>>
%
% * *Current and Voltage of the Battery Pack*
%
% <<fig4.png>>
%
% * *Fuel Cell State-of-Charge and Power*
%
% <<fig5.png>>