%% IEEE VTS Motor Vehicles Challenge 2023
% A Multi-physical Benchmark Problem for Next Generation Energy Management Algorithms
%
%  University of California, Merced | German Aerospace Center (DLR)

%% Introduction
% This brief report has been designed so as to demonstrate the performance
% of the designed Energy Management Algorithm (EMA) by the competitors.
% Please see bellow for more information on the evaluation:
% 
% The selected track corresponds to Track:
Track_no = ind
%% Performance Metrics
% Performance metrics for the corresponding track are as follows:
Metric = ["J_{E}";"J_{SoC}";"J_{TC}";"J_{deg}";"J_{v}";"J_{loss}";"J_{tot}"];
Values = [J_eng;J_SOC;J_T;J_deg;J_v;J_loss;J];
Unit = ["[kWh]";"[s]";"[C]";"[mAh/cycle]";"[s]";"[kWh]";"[-]"];
Description  = ["Total energy consumed by the vehicle";
                "Timespan that SoC constraints are violated";
                "Maximum temperature constraint violation";
                "Lost battery capacity due to battery aging";
                "Derating metric; duration in which the vehicle did not track the reference velocity profile";
                "Total Loss";
                "The final score of the designed EMA"];
Scores = table(Metric,Values,Unit,Description)

%% Results
% * *Reference track*
%
% <<fig1.png>>
%
% * *Control Inputs Generated by the EMA*
%
% <<fig2.png>>
%
% * *State-of-Charge and Temperature of the Battery Pack*
%
% <<fig3.png>>
%
% * *Current and Voltage of the Battery Pack*
%
% <<fig4.png>>
%
% * *Fuel Cell State-of-Charge and Power*
%
% <<fig5.png>>